server:
  port: 8701
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: ai-mcp-gateway-demo-mcp-server-test
  main:
    banner-mode: off
    # stdio - mode open，sse mode -comment
    # web-application-type: none
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0
        type: ASYNC
        instructions: "This server provides weather information tools and resources"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true

logging:
  # stdio - mode open，sse mode -comment
  #  pattern:
  #    console:
  file:
    name: data/log/${spring.application.name}.log


